In [43]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from pathlib import Path

In [44]:
INPUT_PATH = Path.cwd() / "data"

In [45]:
df = pd.read_csv(f"{INPUT_PATH / 'train.csv'}")

In [46]:
for c in df.columns:
    
    if df[c].dtypes == "object":
        df[c] = df[c].astype("category")
        df[c] = df[c].cat.codes

In [47]:
df = df.drop(columns=["LotFrontage", "MasVnrArea", "GarageYrBlt"])

In [48]:
train_X = df.loc[:int(.8*len(df))-1, df.columns != "SalePrice"]
train_y = np.log(df.loc[:int(.8*len(df))-1, "SalePrice"])

valid_X = df.loc[int(.8*len(df)):, df.columns != "SalePrice"]
valid_y = np.log(df.loc[int(.8*len(df)):, "SalePrice"])

In [49]:
train_X.tail()

,Id,MSSubClass,MSZoning,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
1163,1164,90,3,12900,1,-1,3,3,0,4,...,0,0,-1,-1,-1,0,1,2008,8,2
1164,1165,80,3,16157,1,-1,0,3,0,2,...,0,0,-1,-1,-1,0,6,2007,8,4
1165,1166,20,3,9541,1,-1,0,3,0,4,...,0,0,-1,-1,-1,0,9,2009,6,5
1166,1167,20,3,10475,1,-1,0,3,0,0,...,0,0,-1,-1,-1,0,2,2010,8,4
1167,1168,60,3,10852,1,-1,0,3,0,4,...,0,0,-1,-1,-1,0,2,2006,8,4

In [50]:
valid_X.head()

,Id,MSSubClass,MSZoning,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
1168,1169,70,3,13728,1,-1,3,3,0,0,...,90,0,-1,-1,-1,0,7,2008,8,4
1169,1170,60,3,35760,1,-1,0,3,0,1,...,0,0,-1,-1,-1,0,7,2006,8,4
1170,1171,80,3,9880,1,-1,3,3,0,4,...,0,576,2,0,-1,0,7,2008,8,4
1171,1172,20,3,9120,1,-1,3,3,0,4,...,288,0,-1,-1,2,1400,11,2008,8,4
1172,1173,160,1,4017,1,1,0,3,0,4,...,0,0,-1,-1,-1,0,3,2008,8,4

In [51]:
m = RandomForestRegressor(n_jobs=-1)

In [52]:
m.fit(train_X, train_y)

/home/simon/miniconda3/envs/py36/lib/python3.6/site-packages/sklearn/ensemble/forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=-1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [53]:
import math
def rmse(y, yhat):
    return math.sqrt(((y-yhat)**2).mean())

In [54]:
valid_yhat = m.predict(valid_X)
rmse(valid_y, valid_yhat)

0.15531652490578313